Adds an audio command (#97)
Audio handling is introduced, where data is enqueued. Data will be cached to a file when the queue already contains at least one element.
Play, pause, and disconnect (leave early and clear queue) are initially supported.

Closes #38

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -19,12 +19,12 @@ if command -v errcheck >/dev/null; then
 	echo "Found errcheck, checking for ignored errors..."
 	errcheck ./...
 else
-	echo "Warning, couldn't find errcheck, skipping" >&2
+	echo "Warning, couldn't find errcheck, not running" >&2
 fi
 if command -v staticcheck >/dev/null; then
-	echo "Found staticcheck, analyzing..."
+	echo "Found staticheck, performing static analysis..."
 	staticcheck ./...
 else
-	echo "Warning, couldn't find staticcheck, skipping" >&2
+	echo "Warning, coudln't find staticcheck, not running" >&2
 fi
 echo "Finished linting, no issues!"
